name: Release Workflow

on:
  push:
    tags:
      - "v*"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      flutter-version: "2.10.0"

    steps:
      - name: Setup Flutter version
        id: flutter_version
        run: echo "::set-output name=flutter-version::2.10.0"

  build-android:
    needs: setup
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: build/app/outputs/flutter-apk/app-release.apk

  build-ios:
    needs: setup
    runs-on: macos-latest
    environment: Prod
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ needs.setup.outputs.flutter-version }}

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Install CocoaPods dependencies
        run: cd ios && pod install

      - name: Build iOS App (Archive)
        run: flutter build ios --release --no-codesign

      - name: Zip build artifacts
        run: cd build/ios/iphoneos && zip -r ../../ios-app.zip ./*

      - name: Upload iOS build to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ios-app.zip
          path: build/ios-app.zip
